name        = "Marsan"
name8       = "marsan"
locale      = "fr"
variant     = "marsan"
description = "French (Marsan)"
author      = "Claude Marsan"
url         = "https://bepo.fr/wiki/Marsan"
geometry    = "ERGO"
version     = "1.0.0"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃ K   │ ?   │ Ê   │ :   │ –   ┃     │ '   │ Ç   │ !   │ Ù   ┃ *   ┆ ~   ┆
┆     ┃     │ ?   │     │ :   │ -   ┃     │ ’   │     │ !   │     ┃ +   ┆ =   ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ H   │ Y   │ È   │ É   │ G   ┃ M   │ D   │ C   │ V   │ P   ┃*¨   │ µ   ┆
·     ┃     │     │     │     │     ┃     │     │     │     │     ┃*^   ┆ #   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ U   │ I   │ E   │ A   │ O   ┃ L   │ T   │ R   │ S   │ N   ┃ B   │ %   ┆
·     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆ "   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ >   ┃ ;   │ Z   │ W   │ À   │ .   ┃ ,   │ F   │ Q   │ X   │ J   ┃           ·
┆ <   ┃ ;   │     │     │     │     ┃     │     │     │     │     ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
┆     ┃     │     │     │   ¦ │   _ ┃     │   ` │   ^ │     │  *` ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
·     ┃     │     │     │   & │     ┃     │     │     │  *´ │   § ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
·     ┃     │     │   € │     │   ¤ ┃   £ │     │     │   $ │     ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃           ·
┆     ┃   \ │   { │     │   @ │   ( ┃   ) │     │     │   } │   / ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u2019"  # RIGHT SINGLE QUOTATION MARK
1dk_shift   = "\u2019"  # RIGHT SINGLE QUOTATION MARK
